displayName=Teleport animation replacer
author=STRIKERnz
description=Replace teleport animations with alternate animations, sounds, and graphics.
tags=animation,teleport,cowbell,cosmetic
version=1.0.6
plugins=com.strikernz.tpreplacer.TpReplacer
build=standard
